### ISSUE TITLE
ここに修正点や変更点を事細かく書かなくてもいいです。ざっくり書いてください

### ISSUE THREAD

**Issue by kimukimu2** [softcoumobmob/softmob#1]
あざーす！

**Comment by kimukimu2** [comment]
ざっくり変更点書いてくれ、あと変更したら日付と時間入れてくれわかりやすいように

**Comment by kimukimu2** [comment]
削除したら、git addで追加してくれ！！！！じゃないとpullできね！！！！！

**Comment by kimukimu2** [comment]
ほいほい

**Comment by 444495** [comment]
（ここに書かなくてもcommitコメントちゃんと書いておけばcommit履歴見れば済むんじゃないのん）
（と思ったけどこっちのほうがのびのび使えるから何をどうしたかきっちり説明したいときはいいかもね）

**Comment by 444495** [comment]
（何をどうしたかいちいち説明できないという状況は切り分けが上手く行ってない可能性があるけども）

**Comment by kimukimu2** [comment]
まあ、コミットコメントに長々と書いても読みにくいからな、それやったらここに
・◯◯ファイルの　◯◯変更
・◯◯ファイルの◯◯修正
・◯◯削除
・………etcみたいな感じで書いてくれ

**Comment by kimukimu2** [comment]
じゃないと前の人がコミットして、次の人も同じファイルをコミットしたら前の人のコメントは消えてしまうから。別の人がどうなったわからなくなる

**Comment by 444495** [comment]
ここも消えるん？
https://github.com/softcoumobmob/softmob/commits/master

**Comment by kimukimu2** [comment]
そんな場所あるのか！
知らんかったわ。消えてないで

**Comment by kimukimu2** [comment]
てかこっちの方が修正できるし、コミットした時にかなりの量修正したらコメントで書くと読みにくないか？

**Comment by 444495** [comment]
そのへんは感じ方かなあ
ただ、「自分のコードに加えた変更をいちいち周知しなきゃいけない」状況は
そもそもがマズい

**Comment by 444495** [comment]
「今後どうするか」という議論であればcommitコメントはふさわしくないのでぜひこっちでするべき

**Comment by kimukimu2** [comment]
とりあえず、学生やし教えてあげるという気持ちでここはひとつ納得してください。

**Comment by 444495** [comment]
まあ、必要十分にやるっしょ→

**Comment by kimukimu2** [comment]
これぐらいで十分です
例
◯◯ファイルの◯◯メソッド変更
◯◯ファイルの◯◯メソッド変更
ファイルのフィールド◯◯→◯◯に変更
